import io
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

from app.db.models import Meeting


def build_meeting_pdf(meeting: Meeting) -> bytes:
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    y = height - inch

    def line(text: str, size: int = 11, gap: float = 16):
        nonlocal y
        if y < inch:
            c.showPage()
            y = height - inch
        c.setFont("Helvetica", size)
        c.drawString(inch, y, text[:110])
        y -= gap

    c.setFont("Helvetica-Bold", 18)
    c.drawString(inch, y, meeting.title or "Meeting Report")
    y -= 28

    line(f"Platform: {meeting.platform} | Status: {meeting.status}", 10, 14)
    line(f"Date: {meeting.created_at.strftime('%Y-%m-%d %H:%M') if meeting.created_at else '—'}", 10, 14)
    if meeting.duration_seconds:
        line(f"Duration: {meeting.duration_seconds // 60} min", 10, 20)

    if meeting.summary:
        line("Summary", 14, 18)
        for chunk in _wrap(meeting.summary.executive_summary, 90):
            line(chunk, 10, 14)
        y -= 8
        line("Key Decisions", 14, 18)
        for item in meeting.summary.key_decisions or []:
            line(f"• {item}", 10, 14)

    if meeting.action_items:
        line("Action Items", 14, 18)
        for item in meeting.action_items:
            line(f"• {item.task} (Owner: {item.owner}, Due: {item.deadline})", 10, 14)

    if meeting.transcript:
        line("Transcript (excerpt)", 14, 18)
        excerpt = meeting.transcript.full_text[:3000]
        for chunk in _wrap(excerpt, 90):
            line(chunk, 9, 12)

    c.setFont("Helvetica-Oblique", 8)
    c.drawString(inch, 0.5 * inch, f"Generated by KRAI · {datetime.utcnow().isoformat()}Z")
    c.save()
    buffer.seek(0)
    return buffer.read()


def _wrap(text: str, width: int) -> list[str]:
    words = text.split()
    lines, current = [], ""
    for word in words:
        if len(current) + len(word) + 1 > width:
            lines.append(current)
            current = word
        else:
            current = f"{current} {word}".strip()
    if current:
        lines.append(current)
    return lines
